name: Docker Image CI

on:
  push:
    branches: [ "master" ]

concurrency:
  group: docker-image-ci
  cancel-in-progress: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mikeon/curl-impersonate-api:latest

    - name: Push the Docker image
      run: docker push mikeon/curl-impersonate-api:latest
    
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: mikeon/curl-impersonate-api
